language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email:
    recipients:
      - kohchihao@gmail.com
    on_success: always
    on_failure: always
node_js:
  - '9'
git:
  depth: 3
deploy:
  provider: script
  script: ./travis/deploy_gh_pages.sh
  skip-cleanup: true
  keep-history: true
  target-branch: gh-pages
  on:
    branch: master
