language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email:
    recipients:
      - kohchihao@gmail.com
    on_success: always
    on_failure: always
node_js:
  - '9'
git:
  depth: 3
script:
  - yarn build $GITHUB_TOKEN
